name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }} # is a context value to show the output
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: publish js filename
        run: find dist/assets/*.js -type f -exevdir echo 'script-file={}'>> $GITHUB_OUTPUT ';' # used to find the file in the particular js file  AND IN THIS writter we are assigning script-file as a output and use github output
      - name : upload artifacts  # used to store the bulid and dependenices as artifiact  using the path 
        uses : actions/upload-artifact@v4
        with :
          name : dist-flies
          path : |
            dist
            package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name : Get build artifacts # used to dowload the artificat which we dowladed in bulid workflow
        uses : actions/download-artifact@v4
        with : 
          name : dist-flies 
      - name : Output contents
        run : ls  # used to some the contents
      - name: output filename 
        run : echo "${{ needs.build.outputs.script-file}}"
      - name: Deploy
        run: echo "Deploying..."
